### ISSUE TITLE
all in one page

### ISSUE THREAD

**Issue by xi7** [neophtex/AsterLauncher#1]
https://github.com/neophtex/AsterLauncher/assets/67331785/f8dba9a7-dd0e-4959-a5ba-2228e7689d29

list view / search / fav (all in one page)

can you do this?

**Comment by neophtex** [comment]
1. Thank you for the video. You have indeed achieved the functionality you were looking for. However, please understand that our app already has a well-defined design and core features, and we do not intend to alter it.
2. Yeah, I could do it, but it's not something I'm looking to do right now.
