### ISSUE TITLE
F-Droid build not reproducible

### ISSUE THREAD

**Issue by linsui** [neophtex/AsterLauncher#2]
[diff.zip](https://github.com/neophtex/AsterLauncher/files/13439171/diff.zip)

Looks like this is the same problem as https://github.com/anilbeesetti/nextplayer/issues/739#issuecomment-1814502339.

**Comment by neophtex** [comment]
Exactly, I forgot to delete those Google Font XML files. I will update later. I've been quite busy recently. Thank you very much for your help and reminder.

**Comment by licaon-kter** [comment]
So I don't open a new one, https://github.com/neophtex/AsterLauncher/releases/tag/v1.0.8.1 has no APK?

ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/6920186519#L3177

**Comment by neophtex** [comment]
1.already update.

2.I have found an app on F-Droid that is almost identical to mine, with
only a few additional features. When I entered the GitHub repo of that app,
I discovered that the package structure, package names, and class names
code structure are almost the same. However, I did not authorize him to
modify the app name and package name and then publish it on F-Droid. How
should I file a complaint?
This is the url:Easy Launcher
<https://f-droid.org/zh_Hant/packages/app.easy.launcher/index.html>


Licaon_Kter ***@***.***> 於 2024年5月23日 週四 下午10:00寫道：

**Comment by licaon-kter** [comment]
It's called a "fork".

Free software or open source licenses, like GPL3, the one you licensed your software under, allow for this, yes, it's part of then four freedoms.

Eg. Conversations has had a lot of forks over the years, that came and went, like Blabber or Sum7, latest ones are Cheogram, Snikket and Monocles Chat and the one from the main developer Quicksy.

There's no permission to be asked, and F-Dloid allows for this but asks the fork to have their unique name, appid, icon etc, to make it clear it's not the same app.

What is the issue?

**Comment by neophtex** [comment]
According to the provisions of the GPL 3 license, users are required to
declare the source. However, prior to the opponent's upload to F-Droid on
May 17th, his GitHub repository did not declare the source. It was not
until I discovered this situation on May 22nd and opened an issue in his
Easy Launcher repository requesting him to comply with the GPL 3 license,
that he declared the source in the README. This behavior not only violates
the provisions of the GPL 3 license, but also constitutes plagiarism and
misappropriation of my program code. I hope that F-Droid will carefully
examine this situation, protect the rights and interests of developers, and
take appropriate measures. In addition, I also have a recording of him
using my code without declaring the source in the repository. If F-Droid
requires, I can provide this evidence to further prove that his behavior
violates the provisions of the GPL 3 license and constitutes plagiarism and
misappropriation of my program code. I hope that F-Droid will carefully
examine this situation, protect the rights and interests of developers, and
take appropriate measures.

Licaon_Kter ***@***.***> 於 2024年5月24日 週五 下午12:56寫道：

**Comment by licaon-kter** [comment]
> opponent's

That's an odd way to put it, I guess a translation issue :)


Anyway, what's the issue now exactly? Didn't they comply with all that's needed license wise?

**Comment by neophtex** [comment]
As previously mentioned, the developer of "Easy Launcher" added the source
declaration to their README on May 22nd, subsequent to my inquiry. However,
it's worth noting that the app was already uploaded to F-Droid on May 17th
without any mention of the source code. This seems to raise concerns
regarding compliance with the GPL 3 license.

While I understand the common practice of forking in the open-source
community, it's imperative that developers adhere to the requirements of
the GPL 3 license, which include timely source declaration upon
distribution.

I greatly appreciate your attention to this matter and kindly request a
reevaluation considering this additional information. Ensuring compliance
with the GPL 3 license is crucial to maintaining the integrity of the
open-source ecosystem.s

Licaon_Kter ***@***.***> 於 2024年5月24日 週五 下午1:23寫道：

**Comment by linsui** [comment]
Do you mean the credit section in the readme added in https://github.com/DroidWorksStudio/EasyLauncher/commit/722909476c1b19996a690c607173fa909e2248d7?

I thought the correct license notice should be something like

```
Copyright (C) 2024 neophtex
Copyright (C) 2024 DroidWorks Studio

 This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program. If not, see <https://www.gnu.org/licenses/>. 
```

when it's a fork of your code.

**Comment by neophtex** [comment]
Ok,I understand.Sorry for any inconvenience caused, and thanks for your
attention to this matter.



linsui ***@***.***> 於 2024年5月24日 週五 下午1:55寫道：

**Comment by linsui** [comment]
So you can ask them to add the license header properly. And it would be better if you also add the license header to every source code file. :)

**Comment by neophtex** [comment]
Thank you for your suggestion.

linsui ***@***.***> 於 2024年5月24日 週五 下午2:04 寫道：
