### ISSUE TITLE
Font not rendering correctly

### ISSUE THREAD

**Issue by egladman** [neophtex/AsterLauncher#3]
First off, I'm loving the minimalistic launcher and the recent improvements. It's changed how I use my phone for the better.

I think ran into an issue with font rendering on the secondary apps page. I tend to keep my screen fairly dim, and it's very difficult to read the names of my apps even with the brightness turned up all the way.  See screenshots for further context. Is this expected behavior?

## Main Page

![Screenshot_20231204-082723](https://github.com/neophtex/AsterLauncher/assets/8713153/073e8b67-16ad-4a0f-a8dd-51fe92063bc1)

## Secondary Page

![Screenshot_20231204-082712](https://github.com/neophtex/AsterLauncher/assets/8713153/5babab1f-0cd8-4d83-beac-ecd9a3ce00d6)

## Info

App Version: 1.0.6 installed via F-Droid
Android Version: 14
Phone: Pixel 7a

**Comment by neophtex** [comment]
Hello, thank you very much for being willing to contribute. Currently, I have added a theme option for users to switch, which should resolve the issue of unclear fonts. As F-Droid updates take some time, please wait for a while, or you can also download directly from the release. Thanks again for your suggestion and willingness to contribute!

**Comment by egladman** [comment]
Awesome. 👏
